export const SET_TICKETS = "SET_TICKETS"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const SUBST_QUANTITY = "SUBS_QUANTITY"
export const SELECT_SCHEDULE = 'SELECT_SCHEDULE'

// actions para formmulario 
export const SET_TRANSACTION_INFO =  "SET_TRANSACTION_INFO"
export const GET_TRANSACTION_INFO =  "GET_TRANSACTION_INFO"
export const FINISH_TRANSACTION = "FINISH_TRANSACTION"